### ISSUE TITLE
{% else %} tag is not working properly

### ISSUE THREAD

**Issue by imrivera** [oinksoft/dtl#6]
Hi!,

The contents in an {% else %} tag are being rendered even when the "if" condition is true. For example:
```
$ cat test.template
{% if var %}
A
{% else %}
B
{% endif %}
```

And then:

```
$ erl
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.2.1  (abort with ^G)
1> {ok, Cwd} = file:get_cwd().
{ok,"/home/imartinez/branches/esmsc-gw"}
2> application:load(dtl).
ok
3> application:set_env(dtl, template_dirs, [Cwd]).
ok
4> application:start(dtl).
ok
5> dtl:render("test.template",#{}).
{ok,<<"\nB\n\n\n">>}
6> dtl:render("test.template",#{var => true}).
{ok,<<"\nA\n\nB\n\n\n">>}
```

In the second dtl:render call, only "A" should be rendered

**Comment by oinksoft** [comment]
@imrivera Oof that's awful, let me look into this. That functionality is covered by https://github.com/oinksoft/dtl/blob/master/src/dtl_default_library_tests.erl#L131-L145

**Comment by oinksoft** [comment]
@imrivera I'm able to reproduce this in test and will work on a fix later today.

**Comment by oinksoft** [comment]
@imrivera Thanks for reporting this! It should work as expected now. At the same time I identified some unrelated (but similar) issues with `{% ifequal %}` and `{% ifchanged %}` tags which I'll be working on in #7.

**Comment by imrivera** [comment]
Wow! so fast! Thank you very much :-)
